imports:
    - { resource: "../grids/supplier.yaml" }

sylius_grid:
    templates:
        action:
            default: "Grid/Action/default.html.twig"
            create: "Grid/Action/create.html.twig"
            delete: "Grid/Action/delete.html.twig"
            show: "Grid/Action/show.html.twig"
            update: "Grid/Action/update.html.twig"
            apply_transition: "Grid/Action/applyTransition.html.twig"
            links: "Grid/Action/links.html.twig"
            archive: "Grid/Action/archive.html.twig"
        filter:
            string: "Grid/Filter/string.html.twig"
            boolean: "Grid/Filter/boolean.html.twig"
            date: "Grid/Filter/date.html.twig"
            entity: "Grid/Filter/entity.html.twig"
            money: "Grid/Filter/money.html.twig"
            exists: "Grid/Filter/exists.html.twig"
            state: "Grid/Filter/state.html.twig"
            selected_company: "Grid/Filter/selected_company.html.twig"
