sylius_grid:
    grids:
        supplier:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Supplier
            filters:
                name:
                    type: string
                surname:
                    type: string
            fields:
                id: { type: string, sortable: ~ }
                name: { type: string, sortable: ~ }
                surname: { type: string, sortable: ~ }
            limits: [20, 10, 50]
